### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by mistek131995** [Wanwire/FloxcoreXrayKit#5]
![Снимок экрана 2024-06-17 220206](https://github.com/Wanwire/FloxcoreXrayKit/assets/14914380/b3225ad9-dcbf-439c-bd9c-a95cceddd6de)

Hi, I'm new to Swift, can you tell me what I'm doing wrong? Thanks

**Comment by tveerman** [comment]
You've added just the LibXray framework to your project, but XrayKit is a Swift Package. XrayKit includes the LibXray framework, but also defines enum XrayCore and that's what you're missing now. So instead of manually downloading the LibXray.xcframework.zip asset and adding the framework contained in that zip file to your project, add XrayKit as a Swift Package:

0) Remove the LibXray framework from your project
1) On the left hand side (Navigator) click on your LockVPN project file
2) Then select your LockVPN project
3) Go to the Package Dependencies tab
4) Click +
5) At the top right enter "https://github.com/Wanwire/FloxcoreXrayKit" and Add Package
6) At the top of your Swift file import XrayKit instead of LibXray

That should be it.

**Comment by mistek131995** [comment]
Thank you very much for the hint
